[tool.poetry]
name = "jewelduel"
version = "0.1.0"
description = ""
authors = ["Adam Gluck <Adam.Gluck10@Gmail.Com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
